// ── MakerVault Theme ── Modern Tech / Inventory ───────────────────────────
export const T = {
  red:          '#E11D48',
  redLight:     '#FEE2E6',
  redMid:       '#FB7185',
  cream:        '#F8FAFC',
  stone:        '#EEF2F6',
  charcoal:     '#0F172A',
  ink:          '#1E293B',
  muted:        '#64748B',
  faint:        '#94A3B8',
  white:        '#FFFFFF',
  green:        '#16A34A',
  greenLight:   '#DCFCE7',
  amber:        '#D97706',
  amberLight:   '#FEF3C7',
  blue:         '#2563EB',
  blueLight:    '#DBEAFE',
  purple:       '#7C3AED',
  purpleLight:  '#EDE9FE',
  teal:         '#0D9488',
  tealLight:    '#CCFBF1',
  border:       '#E2E8F0',
  borderDark:   '#CBD5E1',
  accent:       '#4F46E5',
  accentLight:  '#EEF2FF',
}

export const statusConfig = {
  available:   { label: 'Available',   color: T.green,  bg: T.greenLight  },
  out_of_stock:{ label: 'Out of Stock',color: T.red,    bg: T.redLight    },
  low_stock:   { label: 'Low Stock',   color: T.amber,  bg: T.amberLight  },
  borrowed:    { label: 'Borrowed',    color: T.amber,  bg: T.amberLight  },
  maintenance: { label: 'Maintenance', color: T.red,    bg: T.redLight    },
  unavailable: { label: 'Unavailable', color: T.muted,  bg: T.stone       },
  pending:     { label: 'Pending',     color: T.blue,   bg: T.blueLight   },
  completed:   { label: 'Returned',    color: T.muted,  bg: T.stone       },
  purchased:   { label: 'Purchased',   color: T.teal,   bg: T.tealLight   },
  active:      { label: 'Borrowed', color: T.amber,  bg: T.amberLight  },
  overdue:     { label: 'Overdue',     color: T.red,    bg: T.redLight    },
  approved:    { label: 'Approved',    color: T.green,  bg: T.greenLight  },
  denied:      { label: 'Declined',    color: T.red,    bg: T.redLight    },
  pay_completed: { label: 'Completed', color: T.green,  bg: T.greenLight  },
  pay_pending:   { label: 'Pending',   color: T.amber,  bg: T.amberLight  },
  pay_failed:    { label: 'Failed',    color: T.red,    bg: T.redLight    },
}
